FROM kalilinux/kali-rolling

RUN apt update && apt upgrade -y

RUN apt install -y \
    nmap \
    nikto \
    sqlmap \
    gobuster \
    metasploit-framework \
    wpscan \
    feroxbuster \
    hydra \
    dirb \
    john \
    tcpdump \
    iputils-ping \
    iproute2 \
    python3 \
    python3-pip 

RUN pip3 install requests --break-system-packages

CMD tail -f /dev/null

